FROM python:3.8.7
WORKDIR /app
COPY requirements-migrations.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY migrations /app/migrations
COPY alembic.ini /app/alembic.ini
COPY app /app/app
CMD ["alembic", "upgrade", "head"]