CREATE TABLE IF NOT EXISTS queries (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    guid VARCHAR(36) UNIQUE NOT NULL,
    query TEXT NOT NULL,
    compiled_query TEXT,
    status VARCHAR(64) NOT NULL,
    error_description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE INDEX IF NOT EXISTS idx_queires_guid ON queries (guid);
