apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-task-broker
    app: task-broker-web
  name: task-broker
#  namespace: dwh-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-task-broker
      app: task-broker-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-task-broker
        app: task-broker-web  
        tier: frontend
        track: stable      
    spec:
      containers:
      - env:
        - name: LOG_DIR
          value: /var/logs
        - name: SERVICE_PORT
          value: "8000"
        - name: DB_CONNECTION_STRING
          value: postgresql+asyncpg://postgres:dwh@10.50.4.110:5432/dwh          
        - name: MQ_CONNECTION_STRING
          value: amqp://dwh:dwh@10.50.4.110:5672/vhdev
        image: 10.50.4.110:5000/task-broker:dev
        imagePullPolicy: Always
        name: task-broker
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: repositorycred
 
      hostAliases:
        - ip: 127.0.0.1        
          hostnames:
          - task-broker.lan                
#      restartPolicy: Never

