"""added run_id

Revision ID: 054ecfbbd1ed
Revises: 5fcb8ec630dd
Create Date: 2022-11-30 11:25:18.092932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054ecfbbd1ed'
down_revision = '5fcb8ec630dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('last_run_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'last_run_id')
    # ### end Alembic commands ###
