"""identity added

Revision ID: 7d2b1198b273
Revises: 054ecfbbd1ed
Create Date: 2022-12-12 11:57:20.455403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2b1198b273'
down_revision = '054ecfbbd1ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('identity_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'identity_id')
    # ### end Alembic commands ###
