apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "task-broker.fullname" . }}-configmap
  labels:
    {{- include "task-broker.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap }}
  dwh_task_broker_{{ $key }}: {{ $value | quote }}
  {{- end }}