apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-broker.fullname" . }}
  labels:
    {{- include "task-broker.labels" . | nindent 4 }}
    {{- if ne .Values.ciEnv "" }}
    environment: {{ .Values.ciEnv }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "task-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "task-broker.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: "{{ .Chart.Name }}-migrations"
          image: "{{ printf "%s-migrations:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}"
          env:
            - name: DWH_TASK_BROKER_DB_MIGRATION_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "task-broker.fullname" . }}-secret
                  key: dwh_task_broker_db_migration_connection_string
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "task-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - secretRef:
                name: {{ include "task-broker.fullname" . }}-secret
            - configMapRef:
                name: {{ include "task-broker.fullname" . }}-configmap
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
