apiVersion: v1
kind: Secret
metadata:
  name: {{ template "task-broker.fullname" . }}-secret
  labels:
    {{- include "task-broker.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  dwh_task_broker_{{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque