apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-broker.fullname" . }}
  labels:
    {{- include "task-broker.labels" . | nindent 4 }}
    {{- if ne .Values.ciEnv "" }}
    environment: {{ .Values.ciEnv }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-broker.selectorLabels" . | nindent 4 }}
